name: Next.js Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies using Yarn or npm (replace with npm if you're using npm)
      - name: Install dependencies
        run: yarn install

      # Build the Next.js project
      - name: Build Next.js
        run: yarn build

      # Optionally, run tests if you have them (this step is optional)
      # - name: Run Tests
      #   run: yarn test
